step_scheduler:
  global_batch_size: 256
  local_batch_size: 1
  ckpt_every_steps: 1000
  # val_every_steps: 50  # will run every x number of gradient steps
  num_epochs: 1

dist_env:
  backend: nccl
  timeout_minutes: 20

rng:
  _target_: nemo_automodel.components.training.rng.StatefulRNG
  seed: 42
  ranked: true

model:
  _target_: nemo_automodel.NeMoAutoModelForImageTextToText.from_pretrained
  pretrained_model_name_or_path: pretrained_models/Qwen3-VL-Bard-4B-Instruct
  attn_implementation: sdpa # sdpa, flash_attention_2
  torch_dtype: "torch.bfloat16"

processor:
  _target_: transformers.AutoProcessor.from_pretrained
  pretrained_model_name_or_path: pretrained_models/Qwen3-VL-Bard-4B-Instruct
  min_pixels: 65536   # 256*256
  max_pixels: 4194304 # 2048*2048

checkpoint:
  enabled: true
  checkpoint_dir: exps/bard_vl_b8_mask_4b_instruct
  model_save_format: torch_save

distributed:
  _target_: nemo_automodel.components.distributed.fsdp2.FSDP2Manager
  dp_size: none
  tp_size: 1
  cp_size: 1
  sequence_parallel: false
  activation_checkpointing: false

loss_fn:
  # _target_: nemo_automodel.components.loss.masked_ce.MaskedCrossEntropy
  # _target_: nemo_automodel.components.loss.mpg_kl.MixturePathGeneralizeKL
  _target_: nemo_automodel.components.loss.weighted_ce.WeightedCrossEntropy

dataset:
  _target_: nemo_automodel.components.datasets.vlm.datasets.bard_vl_dataset
  path_or_dataset: datasets/mixed-8192-b32-tiny
  max_len: 8192
  drop_last: true
  root_dir: datasets
  prior_dist: 'Mask' # Mask, Uniform, Edit, Mix

dataloader:
  _target_: torchdata.stateful_dataloader.StatefulDataLoader
  num_workers: 8
  pin_memory: true
  prefetch_factor: 4
  collate_fn:
    _target_: nemo_automodel.components.datasets.vlm.collate_fns.bard_vl_block_collate_fn
    noise_scheduler:
      _target_: nemo_automodel.utils.scheduler.CondOTScheduler
    model_type: qwen3-vl
    mask_token_id: 151671
    vocab_size: 151646
    pad_token: <|im_end|> # <|im_end|>, <|endoftext|>
    im_end_token: <|im_end|>
    block_size: 8

optimizer:
  _target_: torch.optim.AdamW
  lr: 2e-5
  merger_lr: 2e-5
  visual_lr: 2e-6
  # language_lr: 2e-5
  weight_decay: 0.00
  betas: [0.9, 0.95]

lr_scheduler:
  lr_decay_style: 'cosine'

freeze_config:
  freeze_embeddings: false
  freeze_vision_tower: false
  freeze_language_model: false
