dataset_path: /inspire/hdd/project/chineseculture/public/chenbaoyou/workspace/Dstar-old/datasets/ocrbench_v2_gold_response_gt_64_tokens/hf_dataset
dataset_kwargs:
  load_from_disk: true
task: "ocrbench_v2_64"
test_split: test
output_type: generate_until
doc_to_visual: !function utils.ocrbench_v2_doc_to_visual
doc_to_text: !function utils.ocrbench_v2_doc_to_text
doc_to_target: "answers"
generation_kwargs:
  max_new_tokens: 64
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
process_results: !function utils.ocrbench_v2_process_results
metric_list:
  - metric: ocrbench_v2_accuracy
    aggregation: !function utils.ocrbench_v2_aggregate_accuracy
    higher_is_better: true
metadata:
  - version: 0.0
